package communication;
/**
 * Enum that defines the Answers in the Messages sent to and from the server and client
 */
public enum Answer {
    WAIT_RESPONSE, SUCCEED, FAILED, NO_ROWS_AFFECTED, ALREADY_CONNECTED, INCORRECT_VALUES, ALREADY_LOGGED_IN, CARD_NUMBER_ALREADY_EXIST, ACCOUNT_IS_FROZEN, CREATE_ACCOUNT_SUCCESSFULLY, SELECTED_REPORT_NOT_EXIST,ORDER_STATUS_UPDATED_TO_ARRIVED_NO_REFUND, ORDER_STATUS_UPDATED_TO_ARRIVED_WITH_REFUND
}